[server]
host = "0.0.0.0"
port = 8080

[redis]
url = "redis://127.0.0.1:6379"
pool_size = 10

[rate_limit]
default_limit = 100
burst_size = 200
window_seconds = 60

[cloudflare]
api_token = ""
zone_id = "" 